# Deprecated: blog pages are generated by `node scripts/build_blog_pages.mjs` (canonical).
# This file is kept for reference only; do not run unless you port it to match the .mjs output.
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BLOG = ROOT / "blog"

NAV_MAIN = """
                <a href="{p}index.html" class="nav-item nav-link">Home</a>
                <a href="{p}about.html" class="nav-item nav-link">About</a>
                <div class="nav-item dropdown mega-dropdown">
                    <a href="{p}service.html" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">Services</a>
                    <div class="dropdown-menu mega-menu">
                        <div class="mega-menu-intro">
                            <span class="mega-menu-eyebrow">Our expertise</span>
                            <p class="mega-menu-headline mb-0">Web, creative, cloud, and support.</p>
                        </div>
                        <div class="container-fluid mega-menu-inner">
                            <div class="row g-3 g-lg-4 mega-menu-grid">
                                <div class="col-lg-4 col-md-6"><a href="{p}service-website-development.html" class="mega-item"><div class="mega-icon"><i class="fa fa-laptop-code"></i></div><div class="mega-text"><h6>Website Development</h6><p>Responsive sites that convert</p></div></a></div>
                                <div class="col-lg-4 col-md-6"><a href="{p}service-it-support.html" class="mega-item"><div class="mega-icon"><i class="fa fa-headset"></i></div><div class="mega-text"><h6>IT Support</h6><p>Ongoing technical help</p></div></a></div>
                                <div class="col-lg-4 col-md-6"><a href="{p}service-cloud-services.html" class="mega-item"><div class="mega-icon"><i class="fa fa-cloud"></i></div><div class="mega-text"><h6>Cloud Services</h6><p>Migration and hosting</p></div></a></div>
                            </div>
                            <div class="mega-footer"><a href="{p}service.html" class="btn btn-primary rounded-pill">View all services <i class="fa fa-arrow-right ms-2"></i></a></div>
                        </div>
                    </div>
                </div>
                <a href="{p}portfolio.html" class="nav-item nav-link">Portfolio</a>
                <a href="{p}blog/index.html" class="nav-item nav-link {blog_active}">Blog</a>
                <a href="{p}contact.html" class="nav-item nav-link">Contact</a>
"""

OFFCANVAS = """
                <a href="{p}index.html" class="nav-link py-2 fs-5">Home</a>
                <a href="{p}about.html" class="nav-link py-2 fs-5">About</a>
                <a href="{p}service.html" class="nav-link py-2 fs-5">Services</a>
                <a href="{p}portfolio.html" class="nav-link py-2 fs-5">Portfolio</a>
                <a href="{p}blog/index.html" class="nav-link py-2 fs-5 {blog_active}">Blog</a>
                <a href="{p}contact.html" class="nav-link py-2 fs-5">Contact</a>
"""

FOOTER = """
                <footer class="ft-footer text-light mt-5 wow fadeIn" data-wow-delay="0.1s">
                    <div class="ft-footer-bg" aria-hidden="true"></div>
                    <div class="container position-relative py-5 px-3 px-lg-4">
                        <div class="row g-4 g-xl-5 align-items-start">
                            <div class="col-md-6 col-lg-4">
                                <a href="{p}index.html" class="ft-footer-brand d-inline-flex align-items-center gap-3 text-decoration-none mb-3">
                                    <img src="{p}img/Latest logo.webp" alt="Fraittech" class="ft-footer-logo" width="128" height="128">
                                </a>
                                <p class="ft-footer-lead mb-4">Digital marketing, web, and IT from Nanyuki for businesses across Kenya.</p>
                            </div>
                            <div class="col-6 col-md-3 col-lg-2">
                                <h3 class="ft-footer-heading">Quick links</h3>
                                <ul class="ft-footer-list list-unstyled mb-0">
                                    <li><a href="{p}about.html">About</a></li>
                                    <li><a href="{p}service.html">Services</a></li>
                                    <li><a href="{p}portfolio.html">Portfolio</a></li>
                                    <li><a href="{p}blog/index.html">Blog</a></li>
                                    <li><a href="{p}contact.html">Contact</a></li>
                                </ul>
                            </div>
                            <div class="col-md-6 col-lg-3">
                                <h3 class="ft-footer-heading">Contact</h3>
                                <ul class="ft-footer-contact list-unstyled mb-0">
                                    <li><i class="fa fa-map-marker-alt" aria-hidden="true"></i><span>Nanyuki, Kenya</span></li>
                                    <li><i class="fa fa-phone-alt" aria-hidden="true"></i><a href="tel:+254742451220">+254 742 451 220</a></li>
                                    <li><i class="fa fa-envelope" aria-hidden="true"></i><a href="mailto:info@fraittech.co.ke">info@fraittech.co.ke</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="ft-footer-bottom">
                        <div class="container px-3 px-lg-4">
                            <div class="ft-footer-bottom-inner d-flex flex-column flex-md-row align-items-center justify-content-between gap-3 py-4">
                                <p class="ft-footer-copy mb-0">&copy; 2026 <a href="{p}index.html">Fraittech.co.ke</a></p>
                                <nav class="ft-footer-nav d-flex flex-wrap gap-2" aria-label="Footer">
                                    <a href="{p}help.html">Help</a><span aria-hidden="true">·</span><a href="{p}privacy-policy.html">Privacy</a>
                                </nav>
                            </div>
                        </div>
                    </div>
                </footer>
"""


def shell(title, desc, canonical_path, body_html, og_type="article", blog_active_main=""):
    p = "../"  # from blog/*.html
    blog_nav = NAV_MAIN.format(p=p, blog_active=blog_active_main)
    blog_off = OFFCANVAS.format(p=p, blog_active="fw-semibold" if blog_active_main else "")
    foot = FOOTER.format(p=p)
    safe_desc = html.escape(desc, quote=True)
    safe_title = html.escape(title, quote=True)
    page_url = f"https://fraittech.co.ke/{canonical_path}"
    if og_type == "website":
        ld = {
            "@context": "https://schema.org",
            "@type": "WebPage",
            "name": title,
            "description": desc,
            "url": page_url,
        }
    else:
        ld = {
            "@context": "https://schema.org",
            "@type": "Article",
            "headline": title,
            "description": desc,
            "author": {"@type": "Organization", "name": "Fraittech"},
            "publisher": {"@type": "Organization", "name": "Fraittech", "url": "https://fraittech.co.ke"},
            "mainEntityOfPage": {"@type": "WebPage", "@id": page_url},
        }
    ld_json = json.dumps(ld, ensure_ascii=False)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{html.escape(title, quote=False)}</title>
    <meta name="description" content="{safe_desc}">
    <meta name="robots" content="index, follow">
    <link rel="canonical" href="{html.escape(page_url, quote=True)}">
    <meta property="og:title" content="{safe_title}">
    <meta property="og:description" content="{safe_desc}">
    <meta property="og:url" content="{html.escape(page_url, quote=True)}">
    <meta property="og:type" content="{og_type}">
    <link href="{p}img/favicon/favicon.ico" rel="icon" type="image/x-icon">
    <link href="{p}css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500&family=Jost:wght@500;600;700&display=swap" rel="stylesheet">
    <link href="{p}lib/animate/animate.min.css" rel="stylesheet">
    <link href="{p}css/style.css" rel="stylesheet">
    <link href="{p}css/footer-brand.css" rel="stylesheet">
    <link href="{p}css/blog.css" rel="stylesheet">
    <script type="application/ld+json">
    {ld_json}
    </script>
</head>
<body class="ft-blog-page">
    <div class="ft-topbar py-2 px-lg-5">
        <div class="container-xxl">
            <div class="row g-2 align-items-center">
                <div class="col-md-8">
                    <div class="d-flex flex-wrap gap-3 small text-white">
                        <span><i class="fa fa-phone text-primary me-1"></i><a href="tel:+254742451220" class="text-white text-decoration-none">+254 742 451 220</a></span>
                        <span><i class="fa fa-envelope text-primary me-1"></i><a href="mailto:info@fraittech.co.ke" class="text-white text-decoration-none">info@fraittech.co.ke</a></span>
                        <span><i class="fa fa-map-marker-alt text-primary me-1"></i>Nanyuki, Kenya</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid bg-white p-0">
        <div id="spinner" class="ft-preloader show" role="progressbar" aria-busy="true" aria-label="Loading"><div class="ft-preloader__noise" aria-hidden="true"></div><div class="ft-preloader__content"><div class="ft-preloader__hud"><div class="ft-preloader__label"><span class="ft-preloader__brand">Fraittech</span></div></div></div></div>
        <div class="container-fluid position-relative p-0">
            <nav class="navbar navbar-expand-lg navbar-light ft-navbar px-4 px-lg-5 py-3 py-lg-0">
                <a href="{p}index.html" class="navbar-brand p-0"><img src="{p}img/Latest logo.webp" alt="Fraittech"></a>
                <button class="navbar-toggler ft-nav-toggler d-lg-none" type="button" data-bs-toggle="offcanvas" data-bs-target="#ftNavOffcanvas"><span class="ft-nav-toggler-bars"><span></span><span></span><span></span></span></button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav mx-auto py-0">{blog_nav}</div>
                    <a href="{p}quotation.html" class="btn rounded-pill py-2 px-4 ms-2 d-none d-lg-block">Get a quotation</a>
                </div>
            </nav>
            <div class="offcanvas offcanvas-start ft-nav-offcanvas" tabindex="-1" id="ftNavOffcanvas">
                <div class="offcanvas-header border-bottom"><a href="{p}index.html" class="offcanvas-title"><img src="{p}img/Latest logo.webp" alt="Fraittech"></a><button type="button" class="btn-close" data-bs-dismiss="offcanvas"></button></div>
                <div class="offcanvas-body d-flex flex-column">
                    <nav class="nav flex-column gap-1 flex-grow-1">{blog_off}</nav>
                    <a href="{p}quotation.html" class="btn btn-primary rounded-pill w-100 py-3 mt-2">Get a quotation</a>
                </div>
            </div>
        </div>
        {body_html}
        {foot}
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{p}lib/wow/wow.min.js"></script>
    <script src="{p}js/main.js"></script>
</body>
</html>
"""


def article_page(slug, title, desc, date_published, category, hero_html, content_html):
    canonical = f"blog/{slug}.html"
    hero = f"""
        <header class="ft-blog-hero">
            <div class="container-xxl py-4">
                <p class="mb-2"><a href="index.html" class="text-decoration-none">&larr; All articles</a></p>
                <span class="badge bg-primary">{category}</span>
                <h1 class="mt-2">{title}</h1>
                <p class="lead mb-2">{desc}</p>
                <p class="ft-blog-meta mb-0"><time datetime="{date_published}">{date_published}</time> &middot; Fraittech, Nanyuki</p>
            </div>
        </header>
        <article class="ft-article container-xxl px-3 px-lg-4">
            {hero_html}
            {content_html}
            <p class="mt-4 p-4 bg-light rounded-3"><strong>Work with a Nanyuki-based digital partner.</strong> For websites, branding, cloud, and IT support, <a href="../contact.html">contact Fraittech</a> or <a href="../quotation.html">request a quotation</a>.</p>
        </article>
    """
    html = shell(title, desc, canonical, hero, blog_active_main="active")
    (BLOG / f"{slug}.html").write_text(html, encoding="utf-8")


def main():
    BLOG.mkdir(exist_ok=True)

    # --- Nanyuki articles (5) ---
    article_page(
        "nanyuki-kenya-guide-location-county-travel",
        "Nanyuki, Kenya: Location, County, and How to Get There",
        "Where Nanyuki sits in Laikipia County, how to reach it from Nairobi, Meru, and Isiolo, and what travellers and businesses should know.",
        "2026-04-18",
        "Nanyuki guide",
        """<figure><img src="../img/blog/nanyuki/nanyuki-keywords-local-searches.png" width="1200" height="675" alt="Popular search topics about Nanyuki: travel distances, hospitals, and local information"></figure>""",
        """<p>Nanyuki is one of the best-known towns on the leeward side of Mount Kenya. People search for it alongside practical questions: <strong>which county is Nanyuki in</strong>, <strong>how far from Nairobi</strong>, and <strong>distance from Meru or Isiolo</strong>. This guide answers those questions in one place so visitors, new residents, and businesses can plan confidently.</p>
        <h2>Where is Nanyuki located?</h2>
        <p>Nanyuki lies in <strong>Laikipia County</strong>, at the foot of Mount Kenya. It is a gateway for tourism into the mountain and conservancies, and a service hub for agriculture, retail, and defence communities nearby. If you are verifying an <strong>address in Nanyuki</strong>, always cross-check the estate or landmark with the official postal code (commonly <strong>10400</strong> for Nanyuki town area—confirm with Kenya Post for your exact box or street).</p>
        <h2>Distance and driving time from major towns</h2>
        <p>Road distances vary slightly by route and where you measure from, but typical planning figures are:</p>
        <ul>
            <li><strong>Nairobi to Nanyuki</strong>: roughly <strong>190–200 km</strong> by the main highway via Nyeri; often <strong>3 to 4 hours</strong> by car depending on traffic and stops.</li>
            <li><strong>Meru to Nanyuki</strong>: commonly cited around <strong>80–110 km</strong> depending on whether you travel via Timau or other links—check live maps before travel.</li>
            <li><strong>Isiolo to Nanyuki</strong>: a shorter hop north–south on the corridor toward Mount Kenya; many travellers combine Isiolo and Nanyuki when touring the region.</li>
        </ul>
        <p>Searchers also ask <strong>how many hours from Nairobi to Nanyuki</strong>: budget at least three hours in good conditions; add buffer during rain, night driving, or holiday peaks.</p>
        <h2>Flights and shuttles</h2>
        <p>There is recurring interest in <strong>flights to Nanyuki from Nairobi</strong> and <strong>Nairobi to Nanyuki shuttle</strong> services. Scheduled flights and charter options change seasonally—always confirm current operators, baggage rules, and airstrip locations. Shared shuttles can be cost-effective; private hire offers flexibility for groups or tight schedules.</p>
        <h2>Why this matters for local businesses</h2>
        <p>High search volume for “<strong>Nanyuki Kenya</strong>” and “<strong>Nanyuki town</strong>” shows that people discover the region online first. Hotels, clinics, tour operators, and retailers win when their websites answer these logistics questions clearly, load fast on mobile, and show trustworthy contact details—something our team at Fraittech helps Laikipia businesses implement every week.</p>
        <div class="ft-callout"><strong>Note:</strong> Distances and travel times are estimates for planning. Use your navigation app at the time of travel for live routing.</div>""",
    )

    article_page(
        "nanyuki-nairobi-distance-route-shuttles",
        "Nairobi to Nanyuki Distance, Route Tips, and Shuttle Options",
        "Practical guidance on driving distance, road choices, and transport between Kenya’s capital and Nanyuki.",
        "2026-04-18",
        "Travel",
        """<figure><img src="../img/blog/nanyuki/nanyuki-search-terms-volume.png" alt="Search interest for Nanyuki travel, clubs, weather, and distances"></figure>""",
        """<p>Among the most common queries we see in keyword data are <strong>nairobi to nanyuki distance</strong>, <strong>how far is nanyuki from nairobi</strong>, and <strong>nanyuki distance from nanyuki to nairobi</strong> (people phrase it in many ways). This article standardises the answers.</p>
        <h2>Typical road distance</h2>
        <p>Most routing tools place the drive between <strong>190 km and 205 km</strong> depending on whether you start from central Nairobi or the outskirts, and whether you use the primary highway through Nyeri. The road is mostly paved and busy with tourism and freight—expect enforcement checkpoints and slower traffic through market towns.</p>
        <h2>Driving tips</h2>
        <ul>
            <li>Fill fuel before long climbs; weather near Mount Kenya can change quickly.</li>
            <li>Night driving requires extra caution because of pedestrians, cyclists, and livestock.</li>
            <li>If you are coordinating <strong>meru road</strong> or cross-country itineraries, confirm whether you are routing via Timau or rejoining the main highway.</li>
        </ul>
        <h2>Alternatives to self-drive</h2>
        <p>Shuttle operators and matatu routes fluctuate. Search for “<strong>nairobi to nanyuki shuttle</strong>” plus the month of travel; validate departure points (often specific hotels or terminals). For teams, a chartered minibus can reduce total cost per seat.</p>
        <h2>SEO lesson for transport and hospitality brands</h2>
        <p>Pages that embed structured FAQs (distance, duration, booking links) tend to earn featured snippets. If you run a lodge, clinic, or logistics firm in Nanyuki, pairing accurate travel content with local schema markup helps Google match you to these high-volume searches.</p>""",
    )

    article_page(
        "nanyuki-hotels-accommodation-booking-guide",
        "Hotels and Accommodation in Nanyuki: What Search Data Tells Visitors",
        "A practical overview of where guests look before they book—and how properties can stand out online.",
        "2026-04-18",
        "Hospitality",
        """<figure><img src="../img/blog/nanyuki/nanyuki-high-volume-keywords.png" alt="High-volume searches for Nanyuki hotels, accommodation, and places to visit"></figure>""",
        """<p>Research consistently shows strong interest in <strong>hotels in nanyuki</strong>, <strong>nanyuki hotels</strong>, and <strong>accommodation in nanyuki</strong>. Travellers compare price, proximity to Mount Kenya, and reviews before they commit.</p>
        <h2>What guests expect on your website</h2>
        <ul>
            <li>Clear room categories, photos, and current contact channels (phone, WhatsApp, email).</li>
            <li>Directions from Nairobi with a downloadable pin and estimated drive time.</li>
            <li>Policies on deposits, cancellations, and peak-season pricing.</li>
        </ul>
        <h2>Connecting hospitality with technology</h2>
        <p>Modern lodges and town hotels benefit from integrated booking helpers, fast mobile pages, and secure payment options—including <strong>digital payments</strong> guests already use elsewhere in Kenya. Fraittech builds lightweight marketing sites and connects them to analytics so owners see which keywords (for example “<strong>hotels in nanyuki kenya</strong>”) actually produce enquiries.</p>
        <h2>Content ideas that rank</h2>
        <p>Beyond room listings, helpful articles on <strong>places to visit in nanyuki</strong>, family itineraries, and conference venues keep users on-site longer and support organic visibility.</p>""",
    )

    article_page(
        "nanyuki-weather-attractions-golf-clubs",
        "Nanyuki Weather, Golf, Clubs, and Top Places to Visit",
        "From fairways to forecasts: what draws visitors to Nanyuki and how to plan around the climate.",
        "2026-04-18",
        "Lifestyle &amp; tourism",
        """<figure><img src="../img/blog/nanyuki/nanyuki-cpc-search-demand.png" alt="Search demand for Nanyuki weather, hotels, and related terms"></figure>""",
        """<p>Search trends surface steady interest in <strong>nanyuki weather</strong>, <strong>nanyuki golf club</strong>, <strong>nanyuki country club</strong>, and <strong>places to visit in nanyuki kenya</strong>. Together they paint a picture of a town that mixes outdoor sport, cool-climate leisure, and safari-style excursions.</p>
        <h2>Weather and packing</h2>
        <p>Nanyuki’s elevation means cooler nights year-round. Layered clothing, a windproof jacket, and sun protection are sensible even when midday feels warm. For “<strong>nanyuki weather forecast weather today</strong>” style queries, always check a trusted meteorological source on the morning of your activity—mountain microclimates shift quickly.</p>
        <h2>Golf and member clubs</h2>
        <p>Golf courses and country clubs are part of the town’s identity. Visitors searching <strong>nanyuki clubs in</strong> or <strong>sports club</strong> are often comparing guest policies, green fees, and dining. If you manage a club, publishing transparent visitor rules and photo galleries improves both SEO and guest satisfaction.</p>
        <h2>Itinerary starters</h2>
        <ul>
            <li>Mount Kenya viewpoints and forest walks (with licensed guides where required).</li>
            <li>Wildlife experiences on nearby conservancies.</li>
            <li>Local cafés and farm-to-table stops popular with weekenders from Nairobi.</li>
        </ul>
        <p>Businesses that sponsor events or offer corporate retreats should highlight AV equipment, backup power, and internet reliability—topics technology partners like us document clearly for event bookers.</p>""",
    )

    article_page(
        "nanyuki-hospitals-healthcare-finding-care",
        "Hospitals and Healthcare in Nanyuki: Finding Public and Private Care",
        "How people search for medical services in Nanyuki and how to verify information responsibly.",
        "2026-04-18",
        "Healthcare",
        """<figure><img src="../img/blog/nanyuki/nanyuki-keywords-local-searches.png" alt="Search phrases related to hospitals and services in Nanyuki"></figure>""",
        """<p>Keyword research shows recurring searches for <strong>hospitals in nanyuki</strong>, <strong>hospitals in nanyuki private</strong>, <strong>nanyuki teaching and referral hospital</strong>, <strong>nanyuki cottage hospital</strong>, and <strong>nanyuki hospital contacts</strong>. People need care quickly and often discover options on their phones first.</p>
        <h2>Public and private options</h2>
        <p>Nanyuki hosts a mix of public referral facilities and private clinics. Names and services evolve; always confirm emergency numbers, outpatient hours, and specialist availability directly with the facility. This article does not publish phone numbers because they change—use official hospital websites, signage, or directory services.</p>
        <h2>What healthcare providers should publish online</h2>
        <ul>
            <li>Accurate departments, visiting hours, and escalation paths for emergencies.</li>
            <li>Accessible pages (large text, fast loading) for anxious users on slow networks.</li>
            <li>Privacy-compliant forms instead of asking patients to email sensitive data casually.</li>
        </ul>
        <h2>Technology support</h2>
        <p>Fraittech helps clinics and professional practices with secure hosting, appointment enquiry forms, and IT support so staff spend less time fighting website issues and more time on patient care.</p>
        <div class="ft-callout"><strong>Medical disclaimer:</strong> This content is general information, not medical advice. For emergencies, contact local emergency services or go to the nearest appropriate facility.</div>""",
    )

    # --- Tech articles (20) — Unsplash images (royalty-free via Unsplash License) ---
    tech = [
        ("tech-cloud-migration-smes-kenya", "Cloud Migration for Kenyan SMEs: A Practical Starter Guide", "When moving email, files, or line-of-business apps to the cloud makes sense—and how to reduce risk.", "Cloud", "photo-1451187580459-43490279c0fa", "Server room abstract technology blue"),
        ("tech-cybersecurity-hygiene-kenya-business", "Cybersecurity Basics Every Kenya Business Should Implement This Year", "Passwords, updates, backups, and culture: low-cost habits that stop most common attacks.", "Security", "photo-1563986768609-322da13575f3", "Cybersecurity lock digital concept"),
        ("tech-professional-web-design-roi", "Why Professional Web Design Still Outperforms DIY Templates", "Trust, speed, and conversion: what bespoke design buys you in competitive markets.", "Web", "photo-1460925895917-afdab827c52f", "Analytics dashboard on laptop"),
        ("tech-google-workspace-vs-microsoft-365", "Google Workspace vs Microsoft 365 for Kenyan Teams", "How to choose collaboration stacks based on email history, compliance, and budget.", "Productivity", "photo-1522071820081-009f0129c71c", "Team collaboration meeting"),
        ("tech-hotel-wifi-guest-networks", "Reliable Guest Wi-Fi for Hotels and Lodges Near Nanyuki", "Separate VLANs, fair bandwidth, and branded login pages guests actually understand.", "Hospitality IT", "photo-1558618666-fcd25c85cd64", "Wi-Fi router wireless concept"),
        ("tech-pos-inventory-retail-kenya", "POS and Inventory Systems: What Retailers Should Look For", "Integrations, offline mode, and reporting that matches KRA record-keeping expectations.", "Retail tech", "photo-1556742049-0cfed4f6a45d", "Payment terminal retail"),
        ("tech-backup-strategy-321-rule", "Backup Strategy for Business: The 3-2-1 Rule Explained Simply", "Local copies, cloud copies, and tested restores—why one USB stick is not enough.", "Infrastructure", "photo-1629654297293-c0676bfa18fb", "External hard drive backup"),
        ("tech-remote-work-it-setup", "Remote Work IT Setup: Security Without Friction", "VPN alternatives, device policies, and support workflows that scale past ten staff.", "Remote work", "photo-1588196749597-9ff075ee6b5b", "Video conference remote work"),
        ("tech-api-integration-explained", "API Integrations Explained for Non-Technical Managers", "How systems talk to each other, typical costs, and how to scope an integration project.", "Integration", "photo-1558494949-ef010cbdcc31", "Network cables data center"),
        ("tech-mobile-first-page-speed", "Mobile-First Performance: Why Speed Is an SEO and Sales Issue", "Core Web Vitals, image compression, and hosting choices that affect ranking in Kenya.", "Performance", "photo-1512941937669-90a1b58e7e9c", "Smartphone mobile browsing"),
        ("tech-phishing-awareness-staff-training", "Phishing Awareness: Train Staff to Spot the Latest Tricks", "Simulated tests, clear reporting channels, and policy essentials for SMEs.", "Security", "photo-1633265486064-086b219458ec", "Email security concept"),
        ("tech-domain-hosting-kenya-checklist", "Choosing a Domain and Hosting in Kenya: A Short Checklist", "DNS, SSL, renewal traps, and support quality—questions to ask before you pay.", "Web infrastructure", "photo-1597852074816-d933c7d2b988", "Domain DNS concept keyboard"),
        ("tech-crm-small-business-starter", "CRM for Small Business: Start Simple, Scale Later", "Pipeline visibility without enterprise bloat; integration with WhatsApp and email.", "Sales tech", "photo-1552664730-d307ca884978", "Team CRM meeting"),
        ("tech-firewall-network-segmentation-basics", "Firewalls and Network Segmentation in Plain Language", "Why guest Wi-Fi should never touch your finance VLAN.", "Network", "photo-1544197150-b99a580bb7a8", "Network server lights"),
        ("tech-mpesa-web-payments-integration", "M-Pesa and Web Payments: What Developers and Owners Need to Know", "STK Push, reconciliation, and user experience patterns that reduce drop-off.", "Fintech", "photo-1563013544-824ae1b704d3", "Mobile payment phone"),
        ("tech-iot-smart-buildings-intro", "IoT and Smart Buildings: Where to Start Without Overbuilding", "Sensors, dashboards, and realistic ROI for offices and lodges.", "IoT", "photo-1518770660439-4636190af475", "Electronic circuit board IoT"),
        ("tech-ai-tools-business-responsible-use", "AI Tools for Business Content: Efficient, Responsible Workflows", "Human review, fact checking, and brand safety when using generative AI.", "AI", "photo-1677442136019-21780ecad995", "AI neural abstract"),
        ("tech-ssd-vs-hdd-business-pcs", "SSD vs HDD for Business PCs in 2026", "Why NVMe drives pay for themselves in support time saved.", "Hardware", "photo-1597872200969-2b65d56bd16b", "SSD hard drive components"),
        ("tech-structured-cabling-offices", "Structured Cabling for New Offices: Plan Before You Drywall", "Cable trays, labels, and spare capacity that save money later.", "Infrastructure", "photo-1504384308090-c894fdcc538d", "Office workspace planning technology"),
        ("tech-it-support-retainer-vs-breakfix", "IT Support: Retainer vs Break-Fix for Growing Teams", "How to budget for proactive monitoring and faster incident response.", "IT support", "photo-1516321318423-f06f85e504b3", "IT support technician laptop"),
    ]

    for slug, title, desc, cat, photo, alt in tech:
        src = f"https://images.unsplash.com/{photo}?auto=format&fit=crop&w=1200&q=80"
        article_page(
            slug,
            title,
            desc,
            "2026-04-18",
            cat,
            f"""<figure><img src="{src}" width="1200" height="675" loading="lazy" alt="{alt}"></figure>""",
            f"""<p>{desc}</p>
            <h2>Key takeaways</h2>
            <ul>
                <li>Align technology choices with how your team actually works day to day—not only with vendor marketing.</li>
                <li>Measure outcomes: uptime, ticket volume, lead response time, or checkout completion.</li>
                <li>Partner with specialists when security, compliance, or customer trust is on the line.</li>
            </ul>
            <h2>Deeper dive</h2>
            <p>Organisations across Kenya—from Laikipia hospitality to Nairobi professional services—are modernising stacks in manageable phases. Start with a short audit: identity (email and accounts), data (where files live), customer channels (website and social), and line-of-business apps (finance, bookings, stock). Prioritise fixes that reduce single points of failure, then iterate.</p>
            <p>Fraittech provides website development, cloud guidance, integrations, and ongoing IT support from Nanyuki, with remote coverage nationwide. If you want a roadmap tailored to your budget, <a href="../contact.html">talk to our team</a>.</p>""",
        )

    # Blog index (root-relative paths from blog/index.html use ../ for assets, links to articles are local)
    index_body = """
        <header class="ft-blog-hero"><div class="container-xxl py-4">
            <span class="badge bg-primary">Insights</span>
            <h1 class="mt-2">Fraittech blog: Nanyuki, travel, and technology</h1>
            <p class="lead mb-0">Practical guides inspired by what people search for about Laikipia—and how smart IT helps Kenyan businesses grow.</p>
        </div></header>
        <div class="container-xxl py-5 px-3 px-lg-4">
            <h2 class="h4 mb-4">Nanyuki &amp; Laikipia guides</h2>
            <div class="row g-4 mb-5">
                <div class="col-md-6 col-lg-4"><div class="ft-blog-card"><img class="ft-blog-card__img" src="../img/blog/nanyuki/nanyuki-keywords-local-searches.png" alt=""><div class="ft-blog-card__body"><span class="ft-blog-card__tag">Guide</span><h3 class="ft-blog-card__title"><a href="nanyuki-kenya-guide-location-county-travel.html">Nanyuki location, county &amp; travel</a></h3><p class="ft-blog-card__excerpt">Where Nanyuki is, distances from Nairobi, Meru, and Isiolo.</p></div></div></div>
                <div class="col-md-6 col-lg-4"><div class="ft-blog-card"><img class="ft-blog-card__img" src="../img/blog/nanyuki/nanyuki-search-terms-volume.png" alt=""><div class="ft-blog-card__body"><span class="ft-blog-card__tag">Travel</span><h3 class="ft-blog-card__title"><a href="nanyuki-nairobi-distance-route-shuttles.html">Nairobi to Nanyuki distance &amp; shuttles</a></h3><p class="ft-blog-card__excerpt">Route tips and transport options.</p></div></div></div>
                <div class="col-md-6 col-lg-4"><div class="ft-blog-card"><img class="ft-blog-card__img" src="../img/blog/nanyuki/nanyuki-high-volume-keywords.png" alt=""><div class="ft-blog-card__body"><span class="ft-blog-card__tag">Hospitality</span><h3 class="ft-blog-card__title"><a href="nanyuki-hotels-accommodation-booking-guide.html">Hotels &amp; accommodation</a></h3><p class="ft-blog-card__excerpt">What guests search before they book.</p></div></div></div>
                <div class="col-md-6 col-lg-4"><div class="ft-blog-card"><img class="ft-blog-card__img" src="../img/blog/nanyuki/nanyuki-cpc-search-demand.png" alt=""><div class="ft-blog-card__body"><span class="ft-blog-card__tag">Tourism</span><h3 class="ft-blog-card__title"><a href="nanyuki-weather-attractions-golf-clubs.html">Weather, golf &amp; places to visit</a></h3><p class="ft-blog-card__excerpt">Plan around Nanyuki’s climate and attractions.</p></div></div></div>
                <div class="col-md-6 col-lg-4"><div class="ft-blog-card"><img class="ft-blog-card__img" src="../img/blog/nanyuki/nanyuki-keywords-local-searches.png" alt=""><div class="ft-blog-card__body"><span class="ft-blog-card__tag">Healthcare</span><h3 class="ft-blog-card__title"><a href="nanyuki-hospitals-healthcare-finding-care.html">Hospitals &amp; healthcare</a></h3><p class="ft-blog-card__excerpt">Finding care and publishing trustworthy info online.</p></div></div></div>
            </div>
            <h2 class="h4 mb-4">Technology &amp; business IT</h2>
            <div class="row g-4">
    """

    cards = []
    for slug, title, desc, cat, photo, alt in tech:
        img = f"https://images.unsplash.com/{photo}?auto=format&fit=crop&w=800&q=80"
        cards.append(
            f"""<div class="col-md-6 col-lg-4"><div class="ft-blog-card"><img class="ft-blog-card__img" src="{img}" alt="{alt}"><div class="ft-blog-card__body"><span class="ft-blog-card__tag">{cat}</span><h3 class="ft-blog-card__title"><a href="{slug}.html">{title}</a></h3><p class="ft-blog-card__excerpt">{desc[:100]}…</p></div></div></div>"""
        )
    index_html = shell(
        "Blog | Fraittech Kenya",
        "Guides on Nanyuki, Laikipia travel, and technology for Kenyan businesses.",
        "blog/index.html",
        index_body + "\n".join(cards) + "</div></div>",
        og_type="website",
        blog_active_main="active",
    )
    (BLOG / "index.html").write_text(index_html, encoding="utf-8")


if __name__ == "__main__":
    main()
